ingress:
  className: alb
  sslRedirect: 443
spring:
  applicationName: overtake-springbootsample
  dbPassword: ""
image:
  repository: "533267446521.dkr.ecr.ap-northeast-2.amazonaws.com/overtake-springbootsample"
  tag: "v0.0.2"