apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ekssampleboot-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-075cf2e000ccf6d2f,subnet-013b90b008d277b37
    # 암호화된 secrets.yaml에서 주입된 ACM ARN 사용
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: overtake.live
spec:
  ingressClassName: alb
  rules:
    - host: overtake.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ekssampleboot-svc
                port:
                  number: 80